# Generated by Django 4.2.19 on 2025-02-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='realise_date',
            new_name='release_date',
        ),
    ]
